// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-TV0aj6GXPqZUyxCuBYbyUJHAa6qlw0',
    appId: '1:24739299780:web:298ebbd31998b8058fa491',
    messagingSenderId: '24739299780',
    projectId: 'assessment-app-432f1',
    authDomain: 'assessment-app-432f1.firebaseapp.com',
    storageBucket: 'assessment-app-432f1.appspot.com',
    measurementId: 'G-XYSFDBYDJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IFtvbZXAxRmp8_cO6XoZgSxjIFLABQ0',
    appId: '1:24739299780:android:0131b4a904ca65f38fa491',
    messagingSenderId: '24739299780',
    projectId: 'assessment-app-432f1',
    storageBucket: 'assessment-app-432f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDndN7VLbTV6-melrOu05ValOpuRn_zINI',
    appId: '1:24739299780:ios:9b68ac4fabc5fc4c8fa491',
    messagingSenderId: '24739299780',
    projectId: 'assessment-app-432f1',
    storageBucket: 'assessment-app-432f1.appspot.com',
    iosBundleId: 'com.example.assessmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDndN7VLbTV6-melrOu05ValOpuRn_zINI',
    appId: '1:24739299780:ios:9b68ac4fabc5fc4c8fa491',
    messagingSenderId: '24739299780',
    projectId: 'assessment-app-432f1',
    storageBucket: 'assessment-app-432f1.appspot.com',
    iosBundleId: 'com.example.assessmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb-TV0aj6GXPqZUyxCuBYbyUJHAa6qlw0',
    appId: '1:24739299780:web:e32a5f2ae24ca8328fa491',
    messagingSenderId: '24739299780',
    projectId: 'assessment-app-432f1',
    authDomain: 'assessment-app-432f1.firebaseapp.com',
    storageBucket: 'assessment-app-432f1.appspot.com',
    measurementId: 'G-Q17PVJTES1',
  );
}
